#!/usr/bin/env bash

# Defining the variables
KEY_NAME="school"
KEY_BITS=4096
PASSPHRASE="betty"

# Create the RSA key pair
ssh-keygen -t rsa -b $KEY_BITS -N "$PASSPHRASE" -f "$KEY_NAME"

echo "RSA key pair created:"
echo "Private key: $KEY_NAME"
echo "Public key: $KEY_NAME.pub"
